permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Number Constellations"
id : "" # changeme
description : "See amazing patterns emerge when number spirals are highlighted in different ways"
thumb: "http://minutelabs.io/assets/THUMB_IMAGE" # changeme
version: "0.0.1"

ml_url: "http://minutelabs.io"
ml_library: "http://labs.minutelabs.io/library"
ml_assets: "http://labs.minutelabs.io/assets"
library_path: "library" # changeme

show :
  branding: true
  details: true
  comments: true

